# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('measure_id', models.CharField(blank=True, max_length=255, null=True)),
                ('measure_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Measure_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentAndValueOfCare_Hospital',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_measure_name', models.CharField(max_length=243)),
                ('payment_measure_id', models.CharField(max_length=221)),
                ('payment_category', models.CharField(max_length=248)),
                ('denominator', models.IntegerField(blank=True, null=True)),
                ('payment', models.CharField(max_length=143)),
                ('lower_estimate', models.CharField(max_length=143)),
                ('higher_estimate', models.CharField(max_length=143)),
                ('payment_footnote', models.CharField(max_length=184)),
                ('value_of_care_display_name', models.CharField(max_length=244)),
                ('value_of_care_display_id', models.CharField(max_length=226)),
                ('value_of_care_category', models.CharField(max_length=245)),
                ('value_of_care_footnote', models.CharField(max_length=190)),
                ('measure_start_date', models.DateTimeField(blank=True, null=True)),
                ('measure_end_date', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'PaymentAndValueOfCare_Hospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComplicationsAndDeathsHospital',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('measure_name', models.CharField(max_length=125)),
                ('measure_id', models.CharField(max_length=83)),
                ('compared_to_national', models.CharField(max_length=110)),
                ('denominator', models.IntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('lower_estimate', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('higher_estimate', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('measure_start_date', models.DateTimeField(blank=True, null=True)),
                ('measure_end_date', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ComplicationsAndDeaths_Hospital',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Footnotes',
            fields=[
                ('footnote', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('footnote_text', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Footnotes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('provider_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('county_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('hospital_type', models.CharField(blank=True, max_length=50, null=True)),
                ('hospital_ownership', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_services', models.BooleanField()),
                ('meets_criteria_for_meaningful_use_of_ehrs', models.CharField(max_length=5)),
                ('hospital_overall_rating', models.IntegerField(blank=True, null=True)),
                ('hospital_overall_rating_footnote', models.CharField(blank=True, max_length=50, null=True)),
                ('mortality_national_comparison', models.CharField(blank=True, max_length=50, null=True)),
                ('mortality_national_comparison_footnote', models.CharField(blank=True, max_length=50, null=True)),
                ('safety_of_care_national_comparison', models.CharField(blank=True, max_length=50, null=True)),
                ('safety_of_care_national_comparison_footnote', models.CharField(blank=True, max_length=50, null=True)),
                ('readmission_national_comparison', models.CharField(blank=True, max_length=50, null=True)),
                ('readmission_national_comparison_footnote', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_experience_national_comparison', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_experience_national_comparison_footnote', models.CharField(blank=True, max_length=50, null=True)),
                ('effectiveness_of_care_national_comparison', models.CharField(blank=True, max_length=50, null=True)),
                ('effectiveness_of_care_national_comparison_footnote', models.CharField(blank=True, max_length=50, null=True)),
                ('timeliness_of_care_national_comparison', models.CharField(blank=True, max_length=50, null=True)),
                ('timeliness_of_care_national_comparison_footnote', models.CharField(blank=True, max_length=50, null=True)),
                ('efficient_use_of_medical_imaging_national_comparison', models.CharField(blank=True, max_length=50, null=True)),
                ('efficient_use_of_medical_imaging_national_comparison_footnote', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Hospital',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HospitalReturns_Hospital',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('measure_name', models.CharField(blank=True, max_length=50, null=True)),
                ('measure_id', models.CharField(blank=True, max_length=231, null=True)),
                ('compared_to_national', models.CharField(blank=True, max_length=242, null=True)),
                ('denominator', models.IntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('lower_estimate', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('higher_estimate', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('measure_start_date', models.DateTimeField(blank=True, null=True)),
                ('measure_end_date', models.CharField(blank=True, max_length=10, null=True)),
                ('footnote', models.ForeignKey(blank=True, db_column='footnote', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospitalRanking.Footnotes')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospitalRanking.Hospital')),
            ],
            options={
                'db_table': 'HospitalReturns_Hospital',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedicareSpendingPerPatient_Hospital',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('measure_name', models.CharField(blank=True, max_length=100, null=True)),
                ('measure_id', models.CharField(max_length=6)),
                ('score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('measure_start_date', models.DateTimeField(blank=True, null=True)),
                ('measure_end_date', models.CharField(max_length=10)),
                ('footnote', models.ForeignKey(db_column='footnote', on_delete=django.db.models.deletion.DO_NOTHING, to='hospitalRanking.Footnotes')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospitalRanking.Hospital')),
            ],
            options={
                'db_table': 'MedicareSpendingPerPatient_Hospital',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Normalized_Payment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_measure_name', models.CharField(max_length=243)),
                ('payment_measure_id', models.CharField(max_length=221)),
                ('payment_category', models.CharField(max_length=248)),
                ('payment', models.CharField(max_length=143)),
                ('score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('value_of_care_display_name', models.CharField(max_length=244)),
                ('value_of_care_display_id', models.CharField(max_length=226)),
                ('value_of_care_category', models.CharField(max_length=245)),
                ('provider', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='hospitalRanking.Hospital')),
            ],
            options={
                'db_table': 'Normalized_Payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OutpatientImagingEfficiency_Hospital',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('measure_id', models.CharField(max_length=5)),
                ('measure_name', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('measure_start_date', models.DateTimeField(blank=True, null=True)),
                ('measure_end_date', models.CharField(max_length=10)),
                ('footnote', models.ForeignKey(db_column='footnote', on_delete=django.db.models.deletion.DO_NOTHING, to='hospitalRanking.Footnotes')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospitalRanking.Hospital')),
            ],
            options={
                'db_table': 'OutpatientImagingEfficiency_Hospital',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StructuralMeasures_Hospital',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('measure_name', models.CharField(blank=True, max_length=100, null=True)),
                ('measure_id', models.CharField(max_length=216)),
                ('measure_response', models.BooleanField()),
                ('measure_start_date', models.DateTimeField(blank=True, null=True)),
                ('measure_end_date', models.CharField(max_length=10)),
                ('footnote', models.ForeignKey(db_column='footnote', on_delete=django.db.models.deletion.DO_NOTHING, to='hospitalRanking.Footnotes')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospitalRanking.Hospital')),
            ],
            options={
                'db_table': 'StructuralMeasures_Hospital',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='complicationsanddeathshospital',
            name='footnote',
            field=models.ForeignKey(db_column='footnote', on_delete=django.db.models.deletion.DO_NOTHING, to='hospitalRanking.Footnotes'),
        ),
        migrations.AddField(
            model_name='complicationsanddeathshospital',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospitalRanking.Hospital'),
        ),
    ]
