# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footnote',
            fields=[
                ('footnote', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('footnote_text', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '"Footnotes"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('provider_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('zip_code', models.IntegerField(blank=True, default=0, null=True)),
                ('county_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.IntegerField(blank=True, default=0, null=True)),
                ('hospital_type', models.CharField(blank=True, max_length=50, null=True)),
                ('hospital_ownership', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_services', models.BooleanField(default=False, max_length=50)),
                ('meets_criteria_for_meaningful_use_of_ehrs', models.CharField(blank=True, default='', max_length=1)),
                ('hospital_overall_rating', models.IntegerField(blank=True, default=0, null=True)),
                ('hospital_overall_rating_footnote', models.CharField(blank=True, max_length=50, null=True)),
                ('mortality_national_comparison', models.CharField(blank=True, max_length=50, null=True)),
                ('mortality_national_comparison_footnote', models.CharField(blank=True, max_length=50, null=True)),
                ('safety_of_care_national_comparison', models.CharField(blank=True, max_length=50, null=True)),
                ('safety_of_care_national_comparison_footnote', models.CharField(blank=True, max_length=50, null=True)),
                ('readmission_national_comparison', models.CharField(blank=True, max_length=50, null=True)),
                ('readmission_national_comparison_footnote', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_experience_national_comparison', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_experience_national_comparison_footnote', models.CharField(blank=True, max_length=50, null=True)),
                ('effectiveness_of_care_national_comparison', models.CharField(blank=True, max_length=50, null=True)),
                ('effectiveness_of_care_national_comparison_footnote', models.CharField(blank=True, max_length=50, null=True)),
                ('timeliness_of_care_national_comparison', models.CharField(blank=True, max_length=50, null=True)),
                ('timeliness_of_care_national_comparison_footnote', models.CharField(blank=True, max_length=50, null=True)),
                ('efficient_use_of_medical_imaging_national_comparison', models.CharField(blank=True, max_length=50, null=True)),
                ('efficient_use_of_medical_imaging_national_comparison_footnote', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '"Hospital"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HospitalReturns_Hospital',
            fields=[
                ('provider_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('zip_code', models.IntegerField(blank=True, default=0, null=True)),
                ('county_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.IntegerField(blank=True, default=0, null=True)),
                ('measure_name', models.CharField(blank=True, max_length=50, null=True)),
                ('measure_id', models.CharField(blank=True, default='', max_length=231)),
                ('compared_to_national', models.CharField(blank=True, default='', max_length=242)),
                ('denominator', models.IntegerField(blank=True, default=0, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=33, null=True)),
                ('lower_estimate', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=33, null=True)),
                ('higher_estimate', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=33, null=True)),
                ('footnote', models.CharField(blank=True, default='', max_length=200)),
                ('measure_start_date', models.DateTimeField(blank=True, null=True)),
                ('measure_end_date', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'db_table': '"HospitalReturns_Hospital"',
                'managed': True,
            },
        ),
    ]
