# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitalRanking', '0002_auto_20171119_0837')
    ]

    operations = [
	    migrations.CreateModel(
	            name='Normalized_Payment',
	            fields=[
	                ('id', models.IntegerField(primary_key=True, serialize=False)),
	                ('payment_measure_name', models.CharField(max_length=243)),
	                ('payment_measure_id', models.CharField(max_length=221)),
	                ('payment_category', models.CharField(max_length=248)),
	                ('payment', models.CharField(max_length=143)),
	                ('score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
	                ('value_of_care_display_name', models.CharField(max_length=244)),
	                ('value_of_care_display_id', models.CharField(max_length=226)),
	                ('value_of_care_category', models.CharField(max_length=245)),
	                ('provider', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='hospitalRanking.Hospital')),
	            ],
	            options={
	                'db_table': 'Normalized_Payment',
	                'managed': True,
	            },
	        )
    ]
