# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitalRanking', '0003_auto_20171119_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Normalized_Complications',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('measure_name', models.CharField(max_length=125)),
                ('measure_id', models.CharField(max_length=83)),
                ('compared_to_national', models.CharField(max_length=110)),
                ('denominator', models.IntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospitalRanking.Hospital')),
            ],
            options={
                'db_table': 'Normalized_Complications',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Normalized_Returns',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('measure_name', models.CharField(blank=True, max_length=50, null=True)),
                ('measure_id', models.CharField(blank=True, max_length=231, null=True)),
                ('compared_to_national', models.CharField(blank=True, max_length=242, null=True)),
                ('denominator', models.IntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospitalRanking.Hospital')),
            ],
            options={
                'db_table': 'Normalized_Returns',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Normalized_Timely',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('measure_id', models.CharField(blank=True, max_length=243, null=True)),
                ('measure_name', models.CharField(blank=True, max_length=243, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('sample', models.IntegerField(blank=True, default=0, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospitalRanking.Hospital')),
            ],
            options={
                'db_table': 'Normalized_Timely',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Timely_And_Effective',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('measure_id', models.CharField(blank=True, max_length=243, null=True)),
                ('measure_name', models.CharField(blank=True, max_length=243, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('sample', models.IntegerField(blank=True, default=0, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospitalRanking.Hospital')),
            ],
            options={
                'db_table': 'Timely_And_Effective',
                'managed': True,
            },
        )
    ]
