# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalRanking', '0005_auto_20171119_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normalized_payment',
            old_name='score',
            new_name='n_score',
        ),
        migrations.AddField(
            model_name='normalized_complications',
            name='n_score',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='normalized_returns',
            name='n_score',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='normalized_timely',
            name='n_score',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
