# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalRanking', '0007_auto_20171119_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalized_payment',
            name='payment',
            field=models.CharField(blank=True, max_length=143, null=True),
        ),
        migrations.AlterField(
            model_name='normalized_payment',
            name='payment_category',
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
        migrations.AlterField(
            model_name='normalized_payment',
            name='payment_measure_id',
            field=models.CharField(blank=True, max_length=221, null=True),
        ),
        migrations.AlterField(
            model_name='normalized_payment',
            name='payment_measure_name',
            field=models.CharField(blank=True, max_length=243, null=True),
        ),
        migrations.AlterField(
            model_name='normalized_payment',
            name='value_of_care_category',
            field=models.CharField(blank=True, max_length=245, null=True),
        ),
        migrations.AlterField(
            model_name='normalized_payment',
            name='value_of_care_display_id',
            field=models.CharField(blank=True, max_length=226, null=True),
        ),
        migrations.AlterField(
            model_name='normalized_payment',
            name='value_of_care_display_name',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
    ]
