# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    
    initial = True

    dependencies = [
        ('hospitalRanking', '0008_auto_20171119_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='MD_Hospital',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('education_1', models.CharField(blank=True, max_length=255, null=True)),
                ('education_2', models.CharField(blank=True, max_length=255, null=True)),
                ('education_3', models.CharField(blank=True, max_length=255, null=True)),
                ('education_4', models.CharField(blank=True, max_length=255, null=True)),
                ('education_5', models.CharField(blank=True, max_length=255, null=True)),
                ('education_6', models.CharField(blank=True, max_length=255, null=True)),
                ('field_1', models.CharField(blank=True, max_length=255, null=True)),
                ('field_2', models.CharField(blank=True, max_length=255, null=True)),
                ('field_3', models.CharField(blank=True, max_length=255, null=True)),
                ('field_4', models.CharField(blank=True, max_length=255, null=True)),
                ('field_5', models.CharField(blank=True, max_length=255, null=True)),
                ('field_6', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_1', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_2', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_3', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_4', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_5', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_6', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospitalRanking.Hospital')),
            ],
            options={
                'db_table': 'MD_Hospital',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MD_Score',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospitalRanking.Hospital')),
            ],
            options={
                'db_table': 'MD_Score',
                'managed': True,
            },
        ),
    ]
